name: NASA project
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v2
          with:
            node-version: '16'
        - run: npm run installa
        - run: npm run installb
        - run: npm run build